<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<style>
  body, td{
    font-size: 11px;
  }
  .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
    font-size: 11px;
  }
  .table-borderless tbody tr td, .table-borderless tbody tr th, .table-borderless thead tr th {
        border: none;
    }
    
    .border-bottom {
      border-bottom: 1px solid #eee;
      line-height: 12px;
      height: 12px;
    }
    th {
      background-color: #ec9f2e;
      color: #fff;
    }
    tr.noBorder td {border: 0; }
    
    .table-bordered>tbody>tr.noBorder>td {
      border: 0;
    }
    
  
</style>
<div style="width:900px;">
  <table class="table  table-borderless">
    <tbody>
      <tr>
        <td width="20%"><img src="<?php echo $this->basePath() ?>/img/logo.jpg" width="200px"></td>
        <td style="text-align: center">
          <div style="margin-left:-200px;">
            <h1>Growsari, Inc.</h1>
            <div>L29 Joy Nostalg Center, 17 ADB Ave., Brgy. San Antonio, Pasig City, Philippines</div>
            <div>TIN: 009-237-702-000</div>
          </div>
        </td>
      </tr>
    </tbody>
  </table>

  <table class="table  table-borderless" width="100%">
    <tbody>
      <tr>
        <td colspan="4" style="text-align: center"><h3>SALES ORDER</h3></td>
      </tr>
      <tr>
        <td width="10%"><strong>CUST. NO: </strong></td>
        <TD width="40%"><div class="border-bottom"><?php echo $order['store_id'] ?></div></td>
        <td width="10%"><strong>PO Number: </strong></td>
        <TD><div class="border-bottom"><?php echo $order['id'] ?></div></td>
      </tr>
      <tr>
        <td><strong>CUST NAME: </strong></td>
        <TD><div class="border-bottom"><?php echo $order['name'] ?></div></td>
        <td><strong>DATE:</strong></td>
        <TD><div class="border-bottom"><?php echo $order['created_at'] ?></div></td>
      </tr>
      <tr>
        <td><strong>ADDRESS: </strong></td>
        <td><div class="border-bottom"><?php echo $order['address'] . ', ' . $order['locality'] ?></div></td>
        <td><strong>RECEIPT NO: </strong></td>
        <td><div class="border-bottom"> </div></td>
      </tr>
    </tbody>
  </table>
  <DIV><BR></div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Item Code</th>
        <th>Description</th>
        <th>Unit Price</th>
        <th>Qty.</th>
        <th>Rev. Qty</th>
        <th>Amount (inc. VAT)</th>
        <th>Rev. amount</th>
        <th>Signature</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($order['items']['list'] as $item) : ?>
          <tr>
            <td><?php echo $item['id'] ?></td>
            <td><?php echo $item['sku'] .' - '. $item['volume'].' - '. $item['format'].' - '. $item['quantity'] ?></td>
            <td><?php echo $item['price'] ?></td>
            <td><?php echo $item['quantity'] ?></td>
            <td></td>
            <td><?php echo $item['net_amount'] ?></td>
            <td></td>
            <td></td>        
          </tr>
      <?php endforeach; ?>
          <?php $order['items_cost'] =  $order['amount'] - $order['discount']?>
          <tr class="noBorder">
            <td colspan="4" ></td>
            <td><strong>Total</strong></td>
            <td>₱<?php echo $order['items_cost']?></td>    
            <td colspan="2"></td>
          </tr>
    </tbody>
  </table>
  
  <table class="table table-bordered" style="width:50%" >
    <tbody>
        <tr>
          <td width="20%"><strong>Total Sales</strong></td>
          <td> ₱<?php echo $order['items_cost'] - (($order['items_cost'] * 12)/100) ?></td>
        </tr>
        <tr>
          <td><strong>12% VAT</strong></td>
          <td> ₱<?php echo ($order['items_cost'] * 12)/100 ?> </td>
        </tr>
    </tbody>
  </table>
  
  <table class="table table-bordered" style="width:50%" >
    <tbody>
        <tr>
            <td colspan="2"><h4>Summary</h4></td>
          </tr>
        <tr>
          <td width="30%"><strong>Total item price</strong></td>
          <td> ₱<?php echo $order['items_cost']?></td>
        </tr>
        <tr>
          <td width="30%"><strong>Delivery Charges</strong></td>
          <td> ₱<?php echo $order['delivery_charges'] ?></td>
        </tr>
        <tr>
          <td><strong>Loyalty Points Used</strong></td>
          <td> (-) ₱<?php echo $order['loyalty_points_used'] ?></td>
        </tr>
        <tr>
          <td><strong>Amount to be paid </strong></td>
          <td> ₱<?php echo $order['net_amount'] ?></td>
        </tr>
        <?php if ($order['status'] === 'delivered'): ?>
            <tr>
              <td><strong>Amount Returned</strong></td>
              <td> ₱<?php echo $order['returned_item_amount'] ?></td>
            </tr>
            <tr>
              <td><strong>Amount Collected</strong></td>
              <td> ₱<?php echo $order['amount_collected'] ?></td>
            </tr>
        <?php endif; ?>
    </tbody>
  </table>
  
   <h6>Non available items</h6>
   <table class="table table-bordered" style="width:50%">
    <thead>
      <tr>
        <th>Item Code</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($order['non_available_items']['list'] as $item) : ?>
          <tr>
            <td width="20%"><?php echo $item['id'] ?></td>
            <td><?php echo $item['sku'] .' - '. $item['volume'].' - '. $item['format'].' - '. $item['quantity'] ?></td>
          </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
  
  
  <div class="footer">
    <br>
    <h4>Prepared &  checked by</h4>
    <br><br>
    <div>____________________________________________________________</div>	<br><br>
    <div>BIR Authority to Print No. ____________________	</div>
  </div>

</div>