<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <style>
      @media print {
        body {-webkit-print-color-adjust: exact;}
      }

      body{
        font-size: 11px;
        -webkit-print-color-adjust: exact !important;
      }
      .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
        font-size: 11px;
      }
      .table-borderless tbody tr td, .table-borderless tbody tr th, .table-borderless thead tr th {
        border: none;
      }

      .border-bottom {
        border-bottom: 1px solid #eee;
        line-height: 12px;
        height: 12px;
      }
      th {
        background-color: #ff6501 !important;
        color: #fff;
        border: none !important;
        text-align: center;
        font-size: 15px !important;
        font-weight: 600;
      }
      td {
        text-align: center;
      }
      tr.noBorder td {border: 0; }

      .table-bordered>tbody>tr.noBorder>td {
        border: 0;
      }
      .row-pri td {
        height: 45px;
        font-size: 15px !important;
      }

      .row-main td {
        height: 50px;
        font-size: 15px !important;
      }

      .row-sec {
        height: 15px;
        background-color: #CCCCCC !important;
        font-weight: 600;
        font-size: 12px !important;
      }
      
      .row-value {
        font-size: 20px !important;background-color: #616161;color: #fff;
      }

    </style>
    
    <style type="text/css">
        @media print {
          .table td {
            background-color: transparent !important;
          }
          
          .table th {
            background-color: #ff6501 !important;
            color: #fff !important;
            border: none !important;
            text-align: center !important;
            font-size: 15px !important;
            font-weight: 600 !important;
          }
          
          .table td.row-value {
            font-size: 20px !important;
            background-color: #616161 !important;
          }
          
          .table td.row-value strong {
            color: #fff !important;
          }
        }
      </style>    
    
  </head>
  <body>    
    <div style="width:900px;">
      <table class="table table-bordered">
        <tbody>
          <tr class="row-main">
            <td width="20%"><strong>Order Id</strong></td>
            <td class="row-value"><strong><?php echo $order['order_id'] ?></strong></td>
            <td><strong>Delivery Date</strong></td>
            <td class="row-value"><strong><?php echo $order['delivery_date'] ?></strong></td>
          </tr>
        </tbody>
      </table>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Item Name</th>
            <th>Size</th>
            <th>Code</th>
            <th>Quantity</th>
            <?php if ($order['type'] == 'new') { ?>
                <th>Changed Quantity</th>
            <?php } ?>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($order['items']['list'] as $item) : ?>
              <?php if (($order['type'] == 'all' && $item['quantity'] != 0) || $order['type'] == 'new') { ?>
                  <tr class="row-pri">
                    <td><b><?php echo $item['sku'] ?></b></td>
                    <td style="font-size: 20px !important;"><b><?php echo $item['volume'] ?></b></td>
                    <td><?php echo $item['item_code'] ?></td>
                    <td style="font-size: 20px !important;"><?php echo $item['quantity'] ?></td>
                    <?php if ($order['type'] == 'new') { ?>
                        <?php if ($item['is_added_by_cc'] == 1) { ?>
                            <td style="font-size: 20px !important;"><?php echo $item['quantity'] ?></td>
                        <?php } else if (isset($item['quantity_by_cc']) && ($item['quantity_by_cc'] != $item['quantity_by_wh'])) { ?>
                            <td style="font-size: 20px !important;"><?php echo ($item['quantity_by_cc'] - ($item['quantity_by_wh'] !== null ? $item['quantity_by_wh'] : $item['requested_quantity'])) ?></td>
                        <?php } else { ?>
                            <td style="font-size: 20px !important;"><?php echo 0 ?></td>
                        <?php } ?>
                    <?php } ?>
                    <td style="padding: 0px 10px 0px 10px;"><input style="width: 35px;height: 35px;" type="checkbox" value=""></td>
                  </tr>
                  <tr class="row-sec">
                    <?php if ($order['type'] == 'new') { ?>
                        <td colspan="3"><?php echo $item['super8_name'] ?></td>
                    <?php } else { ?>
                        <td colspan="2"><?php echo $item['super8_name'] ?></td>
                    <?php } ?>
                    <td colspan="3"><?php echo $item['category'] . ' - ' . $item['brand'] ?></td>
                  </tr>
                  <tr>
                    <?php if ($order['type'] == 'new') { ?>
                        <td colspan="6">
                      <?php } else { ?>
                        <td colspan="5">
                      <?php } ?>
                  </tr>
              <?php } ?>
          <?php endforeach; ?>
        </tbody>
      </table>

      <div class="footer">

      </div>

    </div>
  </body>
</html>